name: flutter_animate
description: Add beautiful animated effects & builders in Flutter, via an easy, customizable, unified API.
version: 4.5.2
repository: https://github.com/gskinner/flutter_animate
issue_tracker: https://github.com/gskinner/flutter_animate/issues
topics:
 - animation
 - ui
 - effects
 - widgets
 - widget

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_shaders: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
